demo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

from demo.todos.views import ProjectViewSet, TaskViewSet


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(ProjectViewSet().urls())),
    url(r'^', include(TaskViewSet().urls())),
]

demo/todos/models.py
from django.db import models


DEFAULT_PERMISSIONS = ('add', 'change', 'delete', 'read')


class Project(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['name']
        default_permissions = DEFAULT_PERMISSIONS

    def __str__(self):
        return self.name


class Task(models.Model):
    project = models.ForeignKey(Project, related_name='tasks', on_delete=models.PROTECT)
    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['title']
        default_permissions = DEFAULT_PERMISSIONS

    def __str__(self):
        return self.title

demo/todos/views.py
from simple_viewset.views import ModelViewSet

from .models import Project, Task


class ProjectViewSet(ModelViewSet):
    model = Project


class TaskViewSet(ModelViewSet):
    model = Task
    list_display = ['project', 'title']
    detail_for = 'project'

simple_viewset/views.py
from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth import get_permission_codename
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import get_object_or_404


class ModelViewMixin(PermissionRequiredMixin):
    viewset = None
    detail_for = None
    raise_exception = True

    def get_permission_required(self):
        opts = self.model._meta
        codename = get_permission_codename(self.action, opts)
        permission = '{0}.{1}'.format(opts.app_label, codename)

        return (permission,)

    def get_queryset(self):
        if self.queryset is not None:
            queryset = self.queryset
        elif self.viewset is not None and hasattr(self.viewset, 'get_queryset'):
            queryset = self.viewset.get_queryset(self.request)
        else:
            return self.model._default_manager.all()

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if hasattr(self, 'list_display'):
            context.update({ 'list_display': self.list_display })

        if self.detail_for:
            if issubclass(self.__class__, (ModelListView, ModelCreateView)):
                parent_model = getattr(self.model, self.detail_for).field.related_model
                parent = get_object_or_404(self.get_parent_queryset(parent_model, self.request), pk=self.kwargs.get(self.detail_for))
            else:
                parent = getattr(self.object, self.detail_for)

            context.update({ 'parent': parent })

        return context

    def get_success_url(self):
        url = reverse_lazy('{0}_list'.format(self.model._meta.model_name))
        if self.detail_for:
            parent_pk = getattr(self.object, self.detail_for).pk
            url = reverse_lazy('{0}_list'.format(self.model._meta.model_name), args=(parent_pk,))

        return url

    def get_template_names(self):
        opts = self.model._meta
        return [
            '{}/{}_{}.html'.format(opts.app_label, opts.model_name, self.template_name_suffix),
            'simple_viewset/{}.html'.format(self.template_name_suffix),
        ]

    def get_parent_queryset(self, parent_model, request):
        if self.viewset is not None and hasattr(self.viewset, 'get_parent_queryset'):
            queryset = self.viewset.get_parent_queryset(parent_model, request)
        else:
            queryset = parent_model.objects.all()

        return queryset


class ModelListView(ModelViewMixin, ListView):
    action = 'read'
    list_display = None
    template_name_suffix = 'list'

    def get_queryset(self):
        queryset = super().get_queryset()

        if self.detail_for:
            kwargs = {
                self.detail_for: self.kwargs.get(self.detail_for)
            }
            queryset = queryset.filter(**kwargs)

        return queryset


class ModelDetailView(ModelViewMixin, DetailView):
    action = 'read'
    template_name_suffix = 'detail'


class ModelCreateView(ModelViewMixin, CreateView):
    action = 'add'
    fields = '__all__'
    template_name_suffix = 'form'

    def get_initial(self):
        initial = None
        if self.detail_for:
            initial = {
                self.detail_for: self.kwargs.get(self.detail_for)
            }

        return initial


class ModelUpdateView(ModelViewMixin, UpdateView):
    action = 'change'
    fields = '__all__'
    template_name_suffix = 'form'


class ModelDeleteView(ModelViewMixin, DeleteView):
    action = 'delete'
    template_name_suffix = 'confirm_delete'


class ModelViewSet(object):
    model = None
    detail_for = None
    list_display = None
    list_view_class = ModelListView
    detail_view_class = ModelDetailView
    create_view_class = ModelCreateView
    update_view_class = ModelUpdateView
    delete_view_class = ModelDeleteView

    def urls(self):
        model_name = self.model._meta.model_name
        regexp = ''

        if self.detail_for:
            regexp = self.detail_for + '/(?P<{0}>[0-9]+)/'.format(self.detail_for)

        return [
            url(r'^{0}/{1}$'.format(model_name, regexp), self.get_view('list'), name='{0}_list'.format(model_name)),
            url(r'^{0}/(?P<pk>[0-9]+)/$'.format(model_name), self.get_view('detail'), name='{0}_detail'.format(model_name)),
            url(r'^{0}/add/{1}$'.format(model_name, regexp), self.get_view('create'), name='{0}_add'.format(model_name)),
            url(r'^{0}/(?P<pk>[0-9]+)/update/$'.format(model_name), self.get_view('update'), name='{0}_update'.format(model_name)),
            url(r'^{0}/(?P<pk>[0-9]+)/delete/$'.format(model_name), self.get_view('delete'), name='{0}_delete'.format(model_name)),
        ]

    def get_view(self, option):
        attr = '{0}_view_class'.format(option)
        kwargs = {
            'model': self.model,
            'viewset': self,
            'detail_for': self.detail_for,
        }

        if option == 'list':
            kwargs.update({ 'list_display': self.list_display })
            if self.list_display:
                kwargs.update({ 'template_name_suffix': 'table' })

        return getattr(self, attr, None).as_view(**kwargs)

    def get_parent_queryset(self, parent_model, request):
        return parent_model.objects.all()

demo/todos/templates/todos/project_detail.html
{% extends "simple_viewset/detail.html" %}

{% block content %}
    <div class="row">
        <div class="col"><a href="{% url "task_list" project=object.id %}" class="btn btn-info">Tasks</a></div>
    </div>
    {{ block.super }}
{% endblock content %}

simple_viewset/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <title>Django simple viewset</title>
    </head>

    <body style="padding-top: 15px;">
        <div class="container-fluid">
            {% block breadcrumbs %}
            {% endblock breadcrumbs %}

            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

simple_viewset/templates/simple_viewset/confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load simple_viewset_tags %}

{% block breadcrumbs %}
    <nav>
        <ol class="breadcrumb">
            {% if parent %}
                <li class="breadcrumb-item"><a href="{% url parent|meta:"model"|url_name:"list" %}">{{ parent|meta:"model"|meta:"verbose_name_plural"|capfirst }}</a></li>
                <li class="breadcrumb-item"><a href="{% url parent|meta:"model"|url_name:"detail" parent.id %}">{{ parent }}</a></li>
                <li class="breadcrumb-item"><a href="{% url view.model|url_name:"list" parent.id %}">{{ view.model|meta:"verbose_name_plural"|capfirst }}</a></li>
            {% else %}
                <li class="breadcrumb-item"><a href="{% url view.model|url_name:"list" %}">{{ view.model|meta:"verbose_name_plural"|capfirst }}</a></li>
            {% endif %}
            <li class="breadcrumb-item"><a href="{% url view.model|url_name:"detail" pk=object.id %}">{{ object }}</a></li>
            <li class="breadcrumb-item active">Delete</li>
        </ol>
    </nav>
{% endblock breadcrumbs %}

{% block content %}
    <div class="padding p-t-n">
        <form method="post" role="form" enctype="multipart/form-data">
            {% csrf_token %}

            <p>Delete <strong>{{ object }}</strong>?</p>

            <button type="submit" class="btn btn-danger">Confirm</button>
            <a href="{% url view.model|url_name:"detail" pk=object.id %}" class="btn btn-secondary">Cancel</a>

        </form>
    </div>
{% endblock content %}

simple_viewset/templates/simple_viewset/detail.html
{% extends "base.html" %}
{% load simple_viewset_tags %}

{% block breadcrumbs %}
    <nav>
        <ol class="breadcrumb">
            {% if parent %}
                <li class="breadcrumb-item"><a href="{% url parent|meta:"model"|url_name:"list" %}">{{ parent|meta:"model"|meta:"verbose_name_plural"|capfirst }}</a></li>
                <li class="breadcrumb-item"><a href="{% url parent|meta:"model"|url_name:"detail" parent.id %}">{{ parent }}</a></li>
                <li class="breadcrumb-item"><a href="{% url view.model|url_name:"list" parent.id %}">{{ view.model|meta:"verbose_name_plural"|capfirst }}</a></li>
            {% else %}
                <li class="breadcrumb-item"><a href="{% url view.model|url_name:"list" %}">{{ view.model|meta:"verbose_name_plural"|capfirst }}</a></li>
            {% endif %}
            <li class="breadcrumb-item active">{{ object }}</li>
        </ol>
    </nav>
{% endblock breadcrumbs %}

{% block content %}
    <div class="row">
        {% for field, value in object|fields %}
            <div class="col-sm-4">
                <small class="text-muted">{{ field.verbose_name|capfirst }}</small>
                <p>{{ value }}</p>
            </div>
        {% endfor %}
    </div>

    <div class="row">
        <div class="col">
            <a href="{% url view.model|url_name:"update" pk=object.id %}" class="btn btn-primary">Edit</a>
            <a href="{% url view.model|url_name:"delete" pk=object.id %}" class="btn btn-danger">Delete</a>
        </div>
    </div>
{% endblock content %}

simple_viewset/templates/simple_viewset/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load simple_viewset_tags %}

{% block breadcrumbs %}
    <nav>
        <ol class="breadcrumb">
            {% if parent %}
                <li class="breadcrumb-item"><a href="{% url parent|meta:"model"|url_name:"list" %}">{{ parent|meta:"model"|meta:"verbose_name_plural"|capfirst }}</a></li>
                <li class="breadcrumb-item"><a href="{% url parent|meta:"model"|url_name:"detail" parent.id %}">{{ parent }}</a></li>
                <li class="breadcrumb-item"><a href="{% url view.model|url_name:"list" parent.id %}">{{ view.model|meta:"verbose_name_plural"|capfirst }}</a></li>
            {% else %}
                <li class="breadcrumb-item"><a href="{% url view.model|url_name:"list" %}">{{ view.model|meta:"verbose_name_plural"|capfirst }}</a></li>
            {% endif %}

            {% if object.id %}
                <li class="breadcrumb-item"><a href="{% url view.model|url_name:"detail" pk=object.id %}">{{ object }}</a></li>
                <li class="breadcrumb-item active">Edit</li>
            {% else %}
                <li class="breadcrumb-item active">Add</li>
            {% endif %}
        </ol>
    </nav>
{% endblock breadcrumbs %}

{% block content %}
    <form method="post" role="form" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form | crispy }}

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
            {% if object.id %}
                <a href="{% url view.model|url_name:"detail" pk=object.id %}" class="btn btn-secondary">Cancel</a>
            {% else %}
                {% if parent %}
                    <a href="{% url view.model|url_name:"list" parent.id %}" class="btn btn-secondary">Cancel</a>
                {% else %}
                    <a href="{% url view.model|url_name:"list" %}" class="btn btn-secondary">Cancel</a>
                {% endif %}
            {% endif %}
        </div>
    </form>
{% endblock content %}

simple_viewset/templates/simple_viewset/list.html
{% extends "base.html" %}
{% load simple_viewset_tags %}

{% block breadcrumbs %}
    <nav>
        <ol class="breadcrumb">
            {% if parent %}
                <li class="breadcrumb-item"><a href="{% url parent|meta:"model"|url_name:"list" %}">{{ parent|meta:"model"|meta:"verbose_name_plural"|capfirst }}</a></li>
                <li class="breadcrumb-item"><a href="{% url parent|meta:"model"|url_name:"detail" parent.id %}">{{ parent }}</a></li>
            {% endif %}
            <li class="breadcrumb-item active">{{ view.model|meta:"verbose_name_plural"|capfirst }}</li>
        </ol>
    </nav>
{% endblock breadcrumbs %}

{% block content %}
    <p>
        {% if parent %}
            <a href="{% url view.model|url_name:"add" parent.id %}" class="btn btn-primary">Add</a>
        {% else %}
            <a href="{% url view.model|url_name:"add" %}" class="btn btn-primary">Add</a>
        {% endif %}
    </p>

    <div class="list-group">
        {% for object in object_list %}
            <a href="{% url view.model|url_name:"detail" pk=object.id %}" class="list-group-item list-group-item-action">{{ object }}</a>
        {% endfor %}
    </div>
{% endblock content %}

simple_viewset/templates/simple_viewset/table.html
{% extends "base.html" %}
{% load simple_viewset_tags %}

{% block breadcrumbs %}
    <nav>
        <ol class="breadcrumb">
            {% if parent %}
                <li class="breadcrumb-item"><a href="{% url parent|meta:"model"|url_name:"list" %}">{{ parent|meta:"model"|meta:"verbose_name_plural"|capfirst }}</a></li>
                <li class="breadcrumb-item"><a href="{% url parent|meta:"model"|url_name:"detail" parent.id %}">{{ parent }}</a></li>
            {% endif %}
            <li class="breadcrumb-item active">{{ view.model|meta:"verbose_name_plural"|capfirst }}</li>
        </ol>
    </nav>
{% endblock breadcrumbs %}

{% block content %}
    <p>
        {% if parent %}
            <a href="{% url view.model|url_name:"add" parent.id %}" class="btn btn-primary">Add</a>
        {% else %}
            <a href="{% url view.model|url_name:"add" %}" class="btn btn-primary">Add</a>
        {% endif %}
    </p>

    <table class="table">
        <thead>
            <tr>
                {% for field in view.model|meta:"fields" %}
                    {% if list_display %}
                        {% if field.name in list_display %}
                            <th>{{ field.verbose_name|capfirst }}</th>
                        {% endif %}
                    {% else %}
                        <th>{{ field.verbose_name|capfirst }}</th>
                    {% endif %}
                {% endfor %}
            </tr>
        </thead>

        <tbody>
            {% for object in object_list %}
                <tr>
                    {% for field, value in object|fields %}
                        {% if list_display %}
                            {% if field.name in list_display %}
                                <td><a href="{% url view.model|url_name:"detail" pk=object.id %}">{{ value }}</a></td>
                            {% endif %}
                        {% else %}
                            <td><a href="{% url view.model|url_name:"detail" pk=object.id %}">{{ value }}</a></td>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}